all: sbc
 
sbc: sbc.o ads1115_rpi.o
    gcc -o sbc sbc.o ads1115_rpi.o
 
sbc.o: sbc.c ads1115_rpi.h
    gcc -o sbc.o sbc.c -l wiringPi -l wiringPiDev -c -W -Wall -ansi -pedantic
 
ads1115_rpi.o: ads1115_rpi.c ads1115_rpi.h
    gcc -o ads1115_rpi.o ads1115_rpi.c -c -W -Wall -ansi -pedantic
 
clean:
    rm -rf *.o *~ sbc
